Savepoint - 1.
elvyyy/realt-bot pull request #10
Opened 2022-03-04 19:33 UTC by pinkyfox

2022-03-04 20:39 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/repository/UserRepository.java
> +	Slice<User> findAllByFilter(@Param("price") Integer price,
findAllByProfileFilter

2022-03-04 20:51 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/ApartmentUpdatesPipeline.java
> +public class ApartmentUpdatesPipeline {
it's not a pipeline as i can see, it's more like a queue. please, name it like AppartmentUpdatesQueue

2022-03-04 21:12 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/service/ApartmentService.java
> +			throw new RuntimeException(exc);
log instead of exception

2022-03-04 21:19 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/ApartmentUpdatesPipeline.java
> +			return null;
make optional

2022-03-04 21:30 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/UpdatesProcessor.java
> +	@SneakyThrows
remove

2022-03-04 21:31 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/UpdatesProcessor.java
> +							.forEach(chatId -> apartmentService.sendMessages(chatId, apartmentDto));
extract to MessageService

2022-03-04 21:32 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/UpdatesProcessor.java
> +					bucket.asBlocking().consume(1L);
extract

2022-03-04 21:32 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/UpdatesProcessor.java
> +				pageable);
extract to UserService

2022-03-04 21:35 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/configuration/ConcurrencyConfig.java
> +public class ConcurrencyConfig {
UpdatesExecutorServiceConfig

2022-03-04 21:36 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/properties/ConcurrentProperties.java
> +public class ConcurrentProperties {
Rename

2022-03-04 21:37 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/configuration/ConcurrencyConfig.java
> +	static class ThreadsInitializer {
UpdateProcessorLifecycleManager

2022-03-04 21:38 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/controller/ApartmentController.java
> +@RequestMapping("/apartments")
/api/v1/{token}/apartments, consumes

2022-03-04 21:41 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/controller/ApartmentController.java
> +	public void addApartment(@RequestBody ApartmentDto apartmentDto) {
think

2022-03-04 21:43 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/service/ApartmentService.java
> +public class ApartmentService {
MessageService

2022-03-04 21:44 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/service/ApartmentService.java
> +			throw new RuntimeException(exc);
handle case when a user blocks the bot

2022-03-04 21:45 UTC, elvyyy commented on src/main/resources/application.yml
> +  threads-count: 4
please provide meaningful names

2022-03-05 19:56 UTC, pinkyfox commented on src/main/java/ru/tinderbook/bot/realt/repository/UserRepository.java
> +	Slice<User> findAllByFilter(@Param("price") Integer price,
Fixed

2022-03-05 20:00 UTC, pinkyfox commented on src/main/java/ru/tinderbook/bot/realt/concurrent/ApartmentUpdatesPipeline.java
> +public class ApartmentUpdatesPipeline {
Done

2022-03-05 20:05 UTC, pinkyfox commented on src/main/java/ru/tinderbook/bot/realt/service/ApartmentService.java
> +			throw new RuntimeException(exc);
done

2022-03-05 20:05 UTC, pinkyfox commented on src/main/java/ru/tinderbook/bot/realt/concurrent/ApartmentUpdatesPipeline.java
> +			return null;
done

2022-03-06 04:24 UTC, elvyyy requested changes

2022-03-06 04:24 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/ApartmentAddedEventQueue.java
> +package ru.tinderbook.bot.realt.concurrent;
Maybe let’s use more clear name for the concurrent package? What do you think? 
For instance, we can use a base package ru.tinderbook.bot.realt.event and package ru.tinderbook.bot.realt.event.queue for the queue.

2022-03-06 04:24 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/ApartmentAddedEventQueue.java
> +	private final BlockingQueue<ApartmentAddedEventDto> eventQueue = new LinkedBlockingQueue<>();
What about to add some generic approach to have ability to add other events later.

2022-03-06 04:24 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/ApartmentAddedEventQueue.java
> +
Maybe let’s user some interface type Event that has one method `void process()`. What do you think?

2022-03-06 04:24 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/UpdatesProcessor.java
> +		}
What do you think about to extract all business logic from the processor class?

2022-03-06 04:24 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/dto/ApartmentAddedEventDto.java
> +	private List<String> photos;
Please add `@JsonProperty` annotations to properly serve incoming json objects.

2022-03-06 04:24 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/dto/ApartmentAddedEventDto.java
> +	private List<String> photos;
Please add `@JsonProperty` annotations to properly serve incoming json objects.

2022-03-06 04:26 UTC, elvyyy commented on src/main/java/ru/tinderbook/bot/realt/concurrent/UpdatesProcessor.java
> +		}
I mean `T extends Event`

2022-03-06 10:12 UTC, pinkyfox commented on src/main/java/ru/tinderbook/bot/realt/concurrent/ApartmentAddedEventQueue.java
> +
Event is a model, and it shouldn't contain any business logic

2022-03-06 10:50 UTC, elvyyy approved these changes

2022-03-06 10:53 UTC, merged